services:
  recommendarr:
    image: tannermiddleton/recommendarr:v1.4.4
    environment:
      - PORT=3000
    volumes:
      - ${APP_DATA_DIR}/data/data:/app/server/data
    x-runtipi:
      is_main: true
      internal_port: 3000

x-runtipi:
  schema_version: 2
