version: '3'

services:
  stash:
    image: stashapp/stash:v0.31.0
    ports:
      - "8847:9999"
    environment:
      - STASH_STASH=/media/data/top/
      - STASH_GENERATED=/generated/
      - STASH_METADATA=/metadata/
      - STASH_CACHE=/cache/
      - STASH_PORT=9999
      - PUID=1000
      - PGID=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APP_DATA_DIR}/data/config:/root/.stash
      - ${APP_DATA_DIR}/data/data:/data
      - ${APP_DATA_DIR}/data/metadata:/metadata
      - ${APP_DATA_DIR}/data/cache:/cache
      - ${APP_DATA_DIR}/data/blobs:/blobs
      - ${APP_DATA_DIR}/data/generated:/generated
      - ${ROOT_FOLDER_HOST}/media:/media
    logging:
      driver: json-file
      options:
        max-file: "10"
        max-size: "2m"
    x-runtipi:
      is_main: true
      internal_port: 9999

x-runtipi:
  schema_version: 2
