version: "3.9"
services:
  razor-miniflux-restricted: # Should be exact same name as "id" field in config.json
    container_name: razor-miniflux-restricted # Should be exact same name as "id" field in config.json
    image: romesc/razorminiflux:1748617911 # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
      - FRESHRSS_CONNECTIONSTRING=${FRESHRSS_CONNECTIONSTRING}
      - FRESHRSS_TABLE_PREFIX=${FRESHRSS_TABLE_PREFIX}
      - FRESHRSS_TOP_TABLE_PREFIX=${FRESHRSS_TOP_TABLE_PREFIX}
      - PAGE_SIZE=${PAGE_SIZE}
      - SERVER_PAGE_SIZE=${SERVER_PAGE_SIZE}
      - IS_TOP=${IS_TOP}
      - MARK_STARRED_READ=${MARK_STARRED_READ}
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network # That should not be changed
    labels: # Use your editors search and replace feature to replace all instances of "razor-miniflux-restricted" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.razor-miniflux-restricted-web-redirect.redirectscheme.scheme: https
      traefik.http.services.razor-miniflux-restricted.loadbalancer.server.port: 8080 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.razor-miniflux-restricted-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-miniflux-restricted-insecure.entrypoints: web
      traefik.http.routers.razor-miniflux-restricted-insecure.service: razor-miniflux-restricted
      traefik.http.routers.razor-miniflux-restricted-insecure.middlewares: razor-miniflux-restricted-web-redirect
      # Websecure
      traefik.http.routers.razor-miniflux-restricted.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-miniflux-restricted.entrypoints: websecure
      traefik.http.routers.razor-miniflux-restricted.service: razor-miniflux-restricted
      traefik.http.routers.razor-miniflux-restricted.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.razor-miniflux-restricted-local-insecure.rule: Host(`razor-miniflux-restricted.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-miniflux-restricted-local-insecure.entrypoints: web
      traefik.http.routers.razor-miniflux-restricted-local-insecure.service: razor-miniflux-restricted
      traefik.http.routers.razor-miniflux-restricted-local-insecure.middlewares: razor-miniflux-restricted-web-redirect
      # Local domain secure
      traefik.http.routers.razor-miniflux-restricted-local.rule: Host(`razor-miniflux-restricted.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-miniflux-restricted-local.entrypoints: websecure
      traefik.http.routers.razor-miniflux-restricted-local.service: razor-miniflux-restricted
      traefik.http.routers.razor-miniflux-restricted-local.tls: true
      runtipi.managed: true
