services:
  razor-miniflux-restricted:
    image: romesc/razorminiflux:1776955111
    environment:
      - FRESHRSS_CONNECTIONSTRING=${FRESHRSS_CONNECTIONSTRING}
      - FRESHRSS_TABLE_PREFIX=${FRESHRSS_TABLE_PREFIX}
      - FRESHRSS_TOP_TABLE_PREFIX=${FRESHRSS_TOP_TABLE_PREFIX}
      - PAGE_SIZE=${PAGE_SIZE}
      - SERVER_PAGE_SIZE=${SERVER_PAGE_SIZE}
      - IS_TOP=${IS_TOP}
      - MARK_STARRED_READ=${MARK_STARRED_READ}
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db
    x-runtipi:
      is_main: true
      internal_port: 8080

x-runtipi:
  schema_version: 2
