services:
  openclaw-custom:
    image: 'alpine/openclaw:2026.4.27'
    user: "1000:1000"
    volumes:
      - '${APP_DATA_DIR}/config:/home/node/.openclaw'
      - '${APP_DATA_DIR}/workspace:/home/node/.openclaw/workspace'
    environment:
      - 'HOME=/home/node'
      - 'NODE_ENV=production'
    x-runtipi:
      internal_port: 18789
      is_main: true
x-runtipi:
  schema_version: 2
