version: "3.9"
services:
  razor-iptv: # Should be exact same name as "id" field in config.json
    container_name: razor-iptv # Should be exact same name as "id" field in config.json
    image: romesc/razoriptvdocker:1741565661 # Try to avoid "latest" tag. As it may break configs in the future.
    restart: unless-stopped # Do not change this
    environment:
      - TZ=${TZ} # Can use any env variable. See "environment variables" section in the docs
      - IPTV_URL=${IPTV_URL}
      - IS_TOP=${IS_TOP}
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db # Always start the path with ${APP_DATA_DIR}/data/. This will put all data inside app-data/my-app/data
    ports:
      - ${APP_PORT}:8080
    networks:
      - tipi_main_network # That should not be changed
    labels: # Use your editors search and replace feature to replace all instances of "razor-iptv" with your app name in the traefik labels
      # Main
      traefik.enable: true
      traefik.http.middlewares.razor-iptv-web-redirect.redirectscheme.scheme: https
      traefik.http.services.razor-iptv.loadbalancer.server.port: 8080 # Should be the same as the app internal port so for this example 9443
      # Web
      traefik.http.routers.razor-iptv-insecure.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-iptv-insecure.entrypoints: web
      traefik.http.routers.razor-iptv-insecure.service: razor-iptv
      traefik.http.routers.razor-iptv-insecure.middlewares: razor-iptv-web-redirect
      # Websecure
      traefik.http.routers.razor-iptv.rule: Host(`${APP_DOMAIN}`)
      traefik.http.routers.razor-iptv.entrypoints: websecure
      traefik.http.routers.razor-iptv.service: razor-iptv
      traefik.http.routers.razor-iptv.tls.certresolver: myresolver
      # Local domain
      traefik.http.routers.razor-iptv-local-insecure.rule: Host(`razor-iptv.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-iptv-local-insecure.entrypoints: web
      traefik.http.routers.razor-iptv-local-insecure.service: razor-iptv
      traefik.http.routers.razor-iptv-local-insecure.middlewares: razor-iptv-web-redirect
      # Local domain secure
      traefik.http.routers.razor-iptv-local.rule: Host(`razor-iptv.${LOCAL_DOMAIN}`)
      traefik.http.routers.razor-iptv-local.entrypoints: websecure
      traefik.http.routers.razor-iptv-local.service: razor-iptv
      traefik.http.routers.razor-iptv-local.tls: true
      runtipi.managed: true
