services:
  zerobyte:
    image: ghcr.io/nicotsx/zerobyte:v0.43.2
    restart: unless-stopped
    environment:
      TZ: ${TZ}
      BASE_URL: ${ZEROBYTE_BASE_URL}
      APP_SECRET: ${ZEROBYTE_APP_SECRET}
    volumes:
      - ${APP_DATA_DIR}/data/zerobyte:/var/lib/zerobyte
      - ${ROOT_FOLDER_HOST}:/backups/runtipi-folder:ro
    x-runtipi:
      is_main: true
      internal_port: 4096

x-runtipi:
  schema_version: 2
