services:
  html2rss-web:
    image: html2rss/web:1.2.0
    environment:
      - RACK_ENV=production
      - HTML2RSS_SECRET_KEY=${HTML2RSS_SECRET_KEY}
      - HEALTH_CHECK_TOKEN=${HEALTH_CHECK_TOKEN}
      - AUTO_SOURCE_ENABLED=${AUTO_SOURCE_ENABLED:-false}
      - ASYNC_FEED_REFRESH_ENABLED=false
      - PORT=4000
      - BROWSERLESS_IO_WEBSOCKET_URL=ws://browserless:4002
      - BROWSERLESS_IO_API_TOKEN=html2rss-browserless
      - BOTASAURUS_SCRAPER_URL=http://botasaurus:4010
    depends_on:
      botasaurus:
        condition: service_started
      browserless:
        condition: service_started
    x-runtipi:
      is_main: true
      internal_port: 4000
  botasaurus:
    image: html2rss/botasaurus-scrape-api:latest
    restart: unless-stopped
  browserless:
    image: ghcr.io/browserless/chromium:latest
    restart: unless-stopped
    environment:
      - PORT=4002
      - CONCURRENT=10
      - TOKEN=html2rss-browserless

x-runtipi:
  schema_version: 2
