services:
  kitchenowl:
    image: tombursch/kitchenowl:v0.7.8
    environment:
      - TZ=${TZ}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
    volumes:
      - ${APP_DATA_DIR}/data:/data
    x-runtipi:
      is_main: true
      internal_port: 8080

x-runtipi:
  schema_version: 2
