services:
  reitti:
    image: dedicatedcode/reitti:4.0.2
    volumes:
      - ${APP_DATA_DIR}/data/data:/data
    environment:
      - POSTGIS_HOST=reitti_postgis
      - POSTGIS_PORT=5432
      - POSTGIS_DB=reittidb
      - POSTGIS_USER=reitti
      - POSTGIS_PASSWORD=reitti
      - REDIS_HOST=reitti_redis
      - REDIS_PORT=6379
    depends_on:
      reitti_postgis:
        condition: service_healthy
        restart: true
      reitti_redis:
        condition: service_healthy
      reitti_tile_cache:
        condition: service_healthy
    x-runtipi:
      is_main: true
      internal_port: 8080
  reitti_postgis:
    image: postgis/postgis:17-3.5-alpine
    environment:
      - POSTGRES_USER=reitti
      - POSTGRES_PASSWORD=reitti
      - POSTGRES_DB=reittidb
    volumes:
      - ${APP_DATA_DIR}/data/postgis:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U reitti -d reittidb
      interval: 10s
      timeout: 5s
      retries: 5

  reitti_redis:
    image: redis:7-alpine
    volumes:
      - ${APP_DATA_DIR}/data/redis:/data
    healthcheck:
      test: redis-cli ping
      interval: 10s
      timeout: 5s
      retries: 5

  reitti_tile_cache:
    image: dedicatedcode/reitti-tile-cache:next
    restart: unless-stopped
    healthcheck:
      test: wget --quiet --tries=1 --spider http://127.0.0.1/osm/0/0/0.png || exit 1
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - ${APP_DATA_DIR}/data/tile-cache:/var/cache/nginx

x-runtipi:
  schema_version: 2
