
services:
  blinko:
    image: blinkospace/blinko:1.8.6
    environment:
      - NODE_ENV=production
      - NEXTAUTH_URL=${APP_PROTOCOL-http}://${APP_DOMAIN}
      - NEXT_PUBLIC_BASE_URL=${APP_PROTOCOL-http}://${APP_DOMAIN}
      - NEXTAUTH_SECRET=${BLINKO_NEXTAUTH_SECRET}
      - DATABASE_URL=postgresql://tipi:tipi@blinko-db:5432/blinko
    depends_on:
      blinko-db:
        condition: service_healthy
    volumes:
      - ${APP_DATA_DIR}/data/blinko:/app/.blinko
    healthcheck:
      test: wget --spider -q http://0.0.0.0:1111/
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
    x-runtipi:
      is_main: true
      internal_port: 1111

  blinko-db:
    image: postgres:14
    environment:
      - POSTGRES_DB=blinko
      - POSTGRES_USER=tipi
      - POSTGRES_PASSWORD=tipi
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/db:/var/lib/postgresql/data
    healthcheck:
      test: pg_isready -U tipi -d blinko
      interval: 5s
      timeout: 10s
      retries: 5

x-runtipi:
  schema_version: 2
