version: '3'

services:
  filebrowser-quantum:
    image: gtstef/filebrowser:stable
    volumes:
      - ${APP_DATA_DIR}/data:/home/filebrowser/data
      - ${ROOT_FOLDER_HOST}:/server
    environment:
      - "FILEBROWSER_CONFIG=data/config.yaml" # using our config file at ./data/config.yaml
    restart: unless-stopped
    x-runtipi:
      is_main: true
      internal_port: 80

x-runtipi:
  schema_version: 2
