services:
  rustavoid:
    image: ghcr.io/rodrigomescua/rustavoid:1779748603
    environment:
      - PORT=8080
      - DATABASE_URL=sqlite:///app/data/rustavoid.db?mode=rwc
      - RUST_LOG=rustavoid=info,tower_http=info
    volumes:
      - ${APP_DATA_DIR}/data/data:/app/data
    x-runtipi:
      is_main: true
      internal_port: 8080

x-runtipi:
  schema_version: 2
