version: '3'

services:
  cinephage:
    image: ghcr.io/moldytaint/cinephage:0.12.0
    environment:
      - BETTER_AUTH_SECRET=${BETTER_AUTH_SECRET}
      - TZ=${TZ}
      - PUID=1000
      - PGID=1000
    volumes:
      - ${APP_DATA_DIR}/data/config:/config
      - ${ROOT_FOLDER_HOST}/media:/media
    x-runtipi:
      is_main: true
      internal_port: 3000

x-runtipi:
  schema_version: 2
