version: '3'

services:
  razor-finance:
    image: ghcr.io/rodrigomescua/razorfinance:202512080458
    ports:
      - "8840:8080"
    environment:
      - TZ=${TZ}
    volumes:
      - ${APP_DATA_DIR}/data/db:/app/db
    x-runtipi:
      is_main: true
      internal_port: 8080

x-runtipi:
  schema_version: 2
