services:
  qbitwebui:
    image: ghcr.io/mkbula/qbitwebui:2.44.1
    environment:
      - ENCRYPTION_KEY=${ENCRYPTION_KEY}
    volumes:
      - ${APP_DATA_DIR}/data/data:/data
    x-runtipi:
      is_main: true
      internal_port: 3000

x-runtipi:
  schema_version: 2
