name: Readme Generator

on:
  workflow_dispatch:
  schedule:
    - cron: 0 12 * * *  # 9:00 AM America/Sao_Paulo (UTC-3)
    - cron: 0 21 * * *  # 6:00 PM America/Sao_Paulo (UTC-3)

permissions:
  contents: write
  pull-requests: write

jobs:
  generate-readme-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/create-github-app-token@v2
        id: app-token
        with:
          app-id: ${{ vars.APP_ID }}
          private-key: ${{ secrets.PRIVATE_KEY }}

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Bun
        uses: oven-sh/setup-bun@v2

      - name: Generate new README.md file
        run: bun .github/scripts/readme-generator.ts

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v6
        with:
          token: ${{ steps.app-token.outputs.token }}
          commit-message: |
            docs: regenerate readme app list
          committer: GitHub <noreply@github.com>
          author: GitHub <noreply@github.com>
          branch: bot/readme-update
          title: |
            readme-generator: update readme
          body: |
            Automated README update with latest apps
          labels: bot
          draft: false